/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsTranslatorRouteImport } from './routes/apps/translator'
import { Route as AppsSummarizerRouteImport } from './routes/apps/summarizer'
import { Route as AppsExtractorRouteImport } from './routes/apps/extractor'
import { Route as AppsCodeReviewerRouteImport } from './routes/apps/code-reviewer'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as EntitiesEntityTypeIdRouteImport } from './routes/entities/$entityType/$id'

const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTranslatorRoute = AppsTranslatorRouteImport.update({
  id: '/apps/translator',
  path: '/apps/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSummarizerRoute = AppsSummarizerRouteImport.update({
  id: '/apps/summarizer',
  path: '/apps/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsExtractorRoute = AppsExtractorRouteImport.update({
  id: '/apps/extractor',
  path: '/apps/extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCodeReviewerRoute = AppsCodeReviewerRouteImport.update({
  id: '/apps/code-reviewer',
  path: '/apps/code-reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIdRoute = EntitiesEntityTypeIdRouteImport.update({
  id: '/entities/$entityType/$id',
  path: '/entities/$entityType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/apps/code-reviewer': typeof AppsCodeReviewerRoute
  '/apps/extractor': typeof AppsExtractorRoute
  '/apps/summarizer': typeof AppsSummarizerRoute
  '/apps/translator': typeof AppsTranslatorRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/apps/code-reviewer': typeof AppsCodeReviewerRoute
  '/apps/extractor': typeof AppsExtractorRoute
  '/apps/summarizer': typeof AppsSummarizerRoute
  '/apps/translator': typeof AppsTranslatorRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/apps/code-reviewer': typeof AppsCodeReviewerRoute
  '/apps/extractor': typeof AppsExtractorRoute
  '/apps/summarizer': typeof AppsSummarizerRoute
  '/apps/translator': typeof AppsTranslatorRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/email'
    | '/apps/code-reviewer'
    | '/apps/extractor'
    | '/apps/summarizer'
    | '/apps/translator'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/email'
    | '/apps/code-reviewer'
    | '/apps/extractor'
    | '/apps/summarizer'
    | '/apps/translator'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/email'
    | '/apps/code-reviewer'
    | '/apps/extractor'
    | '/apps/summarizer'
    | '/apps/translator'
    | '/entities/$entityType/$id'
    | '/entities/$entityType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  AppsCodeReviewerRoute: typeof AppsCodeReviewerRoute
  AppsExtractorRoute: typeof AppsExtractorRoute
  AppsSummarizerRoute: typeof AppsSummarizerRoute
  AppsTranslatorRoute: typeof AppsTranslatorRoute
  EntitiesEntityTypeIdRoute: typeof EntitiesEntityTypeIdRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/translator': {
      id: '/apps/translator'
      path: '/apps/translator'
      fullPath: '/apps/translator'
      preLoaderRoute: typeof AppsTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/summarizer': {
      id: '/apps/summarizer'
      path: '/apps/summarizer'
      fullPath: '/apps/summarizer'
      preLoaderRoute: typeof AppsSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/extractor': {
      id: '/apps/extractor'
      path: '/apps/extractor'
      fullPath: '/apps/extractor'
      preLoaderRoute: typeof AppsExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/code-reviewer': {
      id: '/apps/code-reviewer'
      path: '/apps/code-reviewer'
      fullPath: '/apps/code-reviewer'
      preLoaderRoute: typeof AppsCodeReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$id': {
      id: '/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof EntitiesEntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  AppsCodeReviewerRoute: AppsCodeReviewerRoute,
  AppsExtractorRoute: AppsExtractorRoute,
  AppsSummarizerRoute: AppsSummarizerRoute,
  AppsTranslatorRoute: AppsTranslatorRoute,
  EntitiesEntityTypeIdRoute: EntitiesEntityTypeIdRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
